/* Transport-neutral, host-authoritative two-player race session. */
(function(root,factory){const api=factory(root.RaceEngine||(typeof require==='function'&&require('./engine.js')));if(typeof module==='object'&&module.exports)module.exports=api;else root.MultiplayerSession=api.MultiplayerSession;})(typeof globalThis!=='undefined'?globalThis:this,function(Engine){
  const VERSION=2, TICK=1/120;
  const validAction=a=>a==='up'||a==='down'||a==='jump';
  const copy=v=>JSON.parse(JSON.stringify(v));
  class MultiplayerSession {
    constructor(options={}) {
      if(!Engine||!Engine.Race)throw new Error('RaceEngine is required');
      if(options.role!=='host'&&options.role!=='guest')throw new TypeError('role must be host or guest');
      if(!options.clientId||!options.roomEpoch||!options.transport)throw new TypeError('clientId, roomEpoch and transport are required');
      this.role=options.role;this.localSlot=options.role;this.clientId=String(options.clientId);this.roomEpoch=String(options.roomEpoch);this.characterId=options.characterId||'brown';this.transport=options.transport;this.now=options.now||(()=>performance.now());
      this.onState=options.onState||(()=>{});this.onStatus=options.onStatus||(()=>{});this.onEvent=options.onEvent||(()=>{});this.onResult=options.onResult||(()=>{});
      this.engineVersion=1;this.rulesVersion=2;this.phase=options.role==='host'?'waiting':'joining';this.peerId=null;this.race=null;this.raceId=null;this.seed=null;this.tickCount=0;this.seq=0;this.inputSeq=0;this.lastSnapshotTick=-1;this.accumulator=0;this.readySlots=new Set();this.rematchSlots=new Set();this.rematchRequested=false;this.lastRematchAt=0;this.roundCounter=0;this.pendingInputs=new Map();this.expectedInput={host:1,guest:1};this.inputBuffers={host:new Map(),guest:new Map()};this.lastProcessedInputSeq=0;this.lastSentAt=0;this.lastSnapshotAt=0;this.lastHeartbeatAt=0;this.lastHelloAt=0;this.lastHeardAt=this.now();this.startedAt=this.now();this.joinDeadline=this.startedAt+10000;this.joinExpiry=this.startedAt+300000;this.result=null;this.resultAck=false;this.resultSentAt=0;this.startAck=false;this.startSentAt=0;this.eventSeq=0;this.seenEvents=new Set();this.closed=false;
      this.resultStartedAt=0;this.unsubMessage=this.transport.onMessage(message=>this.receive(message));this.unsubDisconnect=this.transport.onDisconnect(()=>this.abort('disconnect'));
      this.status(this.phase);
    }
    status(status,extra={}){this.onStatus({status,phase:this.phase,...extra});}
    state(){return {protocolVersion:VERSION,roomEpoch:this.roomEpoch,raceId:this.raceId,phase:this.phase,localSlot:this.localSlot,peerId:this.peerId,tick:this.tickCount,race:this.race?this.race.snapshot():null,lastProcessedInputSeq:this.lastProcessedInputSeq};}
    emitState(){this.onState(copy(this.state()));}
    send(type,payload={},extra={}) { if(this.closed)return;const message={protocolVersion:VERSION,roomEpoch:this.roomEpoch,raceId:this.raceId,type,seq:++this.seq,senderId:this.clientId,role:this.role,payload,...extra};try{const result=this.transport.send(message);if(result&&typeof result.catch==='function')result.catch(()=>this.abort('send-failed'));}catch(_){this.abort('send-failed');} }
    start(){if(this.closed)return false; if(this.role==='guest'){this.status('joining');this.lastHelloAt=this.now();this.send('hello',{characterId:this.characterId,engineVersion:this.engineVersion,rulesVersion:this.rulesVersion});}else{this.status('waiting-for-guest');}return true;}
    ready(characterId){if(this.closed||!this.validCharacter(characterId)||!['waiting','lobby'].includes(this.phase))return false;this.characterId=String(characterId);this.readySlots.add(this.localSlot);this.send('ready',{characterId:this.characterId});if(this.role==='host'&&this.peerId)this.maybeStart();this.emitState();return true;}
    requestRematch(){if(this.closed||this.phase!=='result'||!this.result)return false;this.rematchRequested=true;this.rematchSlots.add(this.localSlot);this.lastRematchAt=this.now();this.send('rematch-ready',{raceId:this.raceId});this.status('rematch-waiting');if(this.role==='host')this.maybeRematch();this.emitState();return true;}
    input(action){if(!validAction(action)||this.closed||!['countdown','racing'].includes(this.phase))return false;const input={seq:++this.inputSeq,action};if(this.role==='host')this.queueInput('host',input);else {if(this.pendingInputs.size>=64){this.abort('input-overflow');return false;}this.pendingInputs.set(input.seq,input);this.flushInputs();}return true;}
    flushInputs(){if(this.role!=='guest'||!this.pendingInputs.size)return;const now=this.now();if(now-this.lastSentAt<100)return;this.lastSentAt=now;this.send('input',{inputs:Array.from(this.pendingInputs.values()).slice(0,16)});}
    queueInput(slot,input){if(!input||typeof input!=='object'||!validAction(input.action)||!Number.isInteger(input.seq)||input.seq<1)return;const expected=this.expectedInput[slot];if(input.seq<expected)return;if(input.seq===expected){this.applyInput(slot,input);this.expectedInput[slot]++;while(this.inputBuffers[slot].has(this.expectedInput[slot])){const next=this.inputBuffers[slot].get(this.expectedInput[slot]);this.inputBuffers[slot].delete(this.expectedInput[slot]);this.applyInput(slot,next);this.expectedInput[slot]++;}}else if(input.seq-expected<=64&&!this.inputBuffers[slot].has(input.seq))this.inputBuffers[slot].set(input.seq,{...input,receivedAt:this.now()});}
    applyInput(slot,input){if(!this.race)return;const racer=slot==='host'?this.race.player:this.race.opponent;if(input.action==='up')this.race.move(racer,-1);else if(input.action==='down')this.race.move(racer,1);else this.race.jump(racer);if(slot==='guest')this.lastProcessedInputSeq=input.seq;}
    maybeStart(){if(this.role==='host'&&this.peerId&&this.readySlots.has('host')&&this.readySlots.has('guest')&&!this.race)this.beginRound();}
    maybeRematch(){if(this.role==='host'&&this.phase==='result'&&this.resultAck&&this.rematchSlots.has('host')&&this.rematchSlots.has('guest'))this.beginRound();}
    resetRound(){this.result=null;this.resultAck=false;this.resultSentAt=0;this.resultStartedAt=0;this.startAck=false;this.startSentAt=0;this.inputSeq=0;this.lastProcessedInputSeq=0;this.pendingInputs.clear();this.inputBuffers={host:new Map(),guest:new Map()};this.expectedInput={host:1,guest:1};this.readySlots.clear();this.tickCount=0;this.lastSnapshotTick=-1;this.eventSeq=0;this.seenEvents.clear();this.accumulator=0;this.lastSentAt=0;this.lastSnapshotAt=0;this.lastHeartbeatAt=0;this.lastHeardAt=this.now();this.rematchSlots.clear();this.rematchRequested=false;}
    beginRound(){this.resetRound();this.seed=(Math.floor(this.now()*1000)^this.seq^0x51f15e^++this.roundCounter)>>>0;this.raceId=this.roomEpoch+'-'+this.roundCounter+'-'+this.seed.toString(36);this.race=new Engine.Race(this.characterId,this.peerCharacterId||'gray',this.seed,0,{mode:'multiplayer'});this.phase='starting';this.startStartedAt=this.now();this.broadcastStart();this.emitState();}
    broadcastStart(){this.startSentAt=this.now();this.send('start',{snapshot:this.race.snapshot(),roundCounter:this.roundCounter,startAt:this.now(),characters:{host:this.characterId,guest:this.peerCharacterId||'gray'},engineVersion:this.engineVersion,rulesVersion:this.rulesVersion});}
    receive(message){
      if(this.closed||!message||typeof message!=='object'||message.protocolVersion!==VERSION||message.roomEpoch!==this.roomEpoch||typeof message.type!=='string')return;
      try{if(JSON.stringify(message).length>262144)return;}catch(_){return;}
      if(message.senderId===this.clientId||!message.senderId||message.to&&message.to!==this.clientId)return;
      if(message.type==='hello'){if(this.role==='host')this.receiveHello(message);return;}
      if((!this.peerId||message.senderId!==this.peerId)&&message.type!=='welcome'&&message.type!=='reject')return;
      if(message.role!==(this.role==='host'?'guest':'host'))return;
      if(message.raceId!==this.raceId&&message.type!=='welcome'&&message.type!=='reject'&&message.type!=='ready'&&message.type!=='start')return;
      this.lastHeardAt=this.now();
      switch(message.type){case 'welcome':this.receiveWelcome(message);break;case 'reject':this.abort(message.payload?.reason==='version'?'version-mismatch':'room-full');break;case 'ready':this.receiveReady(message);break;case 'start':this.receiveStart(message);break;case 'start-ack':if(this.role==='host'&&this.phase==='starting'){this.startAck=true;this.phase='countdown';this.emitState();}break;case 'rematch-ready':this.receiveRematch(message);break;case 'input':if(this.role==='host')this.receiveInputs(message);break;case 'snapshot':if(this.role==='guest')this.receiveSnapshot(message);break;case 'heartbeat':this.send('heartbeat-ack',{});break;case 'heartbeat-ack':break;case 'result':if(this.role==='guest')this.receiveResult(message);break;case 'result-ack':if(this.role==='host'&&this.result&&message.payload&&message.payload.resultId===this.result.resultId){this.resultAck=true;this.maybeRematch();}break;case 'abort':this.abort((message.payload&&message.payload.reason)||'peer-abort',false);break;}
    }
    receiveHello(message){if(message.role!=='guest'||!message.payload||typeof message.payload.characterId!=='string'||!this.validCharacter(message.payload.characterId))return;if(message.payload.engineVersion!==this.engineVersion||message.payload.rulesVersion!==this.rulesVersion){this.sendTo(message.senderId,'reject',{reason:'version'});return;}if(this.peerId&&this.peerId!==message.senderId){this.sendTo(message.senderId,'reject',{reason:'room-full'});return;}const first=!this.peerId;this.peerId=message.senderId;if(first)this.peerCharacterId=message.payload.characterId;this.lastHeardAt=this.now();this.send('welcome',{hostId:this.clientId,guestId:this.peerId,hostCharacterId:this.characterId,guestCharacterId:this.peerCharacterId,engineVersion:this.engineVersion,rulesVersion:this.rulesVersion});if(first&&['waiting','lobby'].includes(this.phase)){this.phase='lobby';this.status('guest-joined');this.emitState();}}
    sendTo(peerId,type,payload){const message={protocolVersion:VERSION,roomEpoch:this.roomEpoch,raceId:this.raceId,type,seq:++this.seq,senderId:this.clientId,role:this.role,to:peerId,payload};try{this.transport.send(message);}catch(_){}}
    receiveWelcome(message){if(this.role!=='guest'||message.to&&message.to!==this.clientId||!message.payload||message.payload.guestId!==this.clientId||message.payload.engineVersion!==this.engineVersion||message.payload.rulesVersion!==this.rulesVersion||!this.validCharacter(message.payload.hostCharacterId))return;if(this.phase==='joining'){this.peerId=message.senderId;this.peerCharacterId=message.payload.hostCharacterId;this.phase='lobby';this.status('joined');this.emitState();}}
    validCharacter(id){return typeof id==='string'&&Engine.CHARACTERS.some(c=>c.id===id);}
    receiveReady(message){const character=message.payload&&message.payload.characterId;if(!this.validCharacter(character)||this.phase!=='lobby'||this.raceId!==null)return;const slot=message.role;this.readySlots.add(slot);if(slot==='guest')this.peerCharacterId=character;if(this.role==='host')this.maybeStart();this.emitState();}
    receiveStart(message){if(this.role!=='guest'||!message.payload||!message.payload.snapshot||message.payload.engineVersion!==this.engineVersion||message.payload.rulesVersion!==this.rulesVersion||!Number.isInteger(message.payload.roundCounter))return;if(this.race&&message.raceId===this.raceId&&message.payload.roundCounter===this.roundCounter){this.send('start-ack',{});return;}if(message.payload.roundCounter!==this.roundCounter+1||(this.phase!=='lobby'&&!(this.phase==='result'&&this.rematchRequested)))return;try{const next=Engine.Race.fromSnapshot(message.payload.snapshot);this.resetRound();this.roundCounter=message.payload.roundCounter;this.race=next;this.raceId=message.raceId;this.seed=this.race.seed;this.phase='countdown';this.send('start-ack',{});this.emitState();}catch(_){this.abort('invalid-start');}}
    receiveRematch(message){if(this.phase!=='result'||!this.result||!message.payload||message.payload.raceId!==this.raceId)return;this.rematchSlots.add(message.role);if(!this.rematchRequested)this.status('rematch-offered');if(this.role==='host')this.maybeRematch();}
    receiveInputs(message){if(!['countdown','racing'].includes(this.phase))return;const inputs=message.payload&&message.payload.inputs;if(!Array.isArray(inputs)||inputs.length>16)return;for(const input of inputs)this.queueInput('guest',input);}
    receiveSnapshot(message){const payload=message.payload||{};if(this.result||!Number.isInteger(payload.tick)||payload.tick<=this.lastSnapshotTick||!payload.snapshot||!['countdown','racing','result'].includes(payload.phase))return;try{this.race=Engine.Race.fromSnapshot(payload.snapshot);}catch(_){return;}this.lastSnapshotTick=payload.tick;this.tickCount=payload.tick;this.phase=payload.phase||this.phase;const ack=payload.lastProcessedInputSeq||0;for(const seq of this.pendingInputs.keys())if(seq<=ack)this.pendingInputs.delete(seq);if(Array.isArray(payload.events))for(const event of payload.events){const key=event&&event.eventSeq;if(!Number.isInteger(key)||this.seenEvents.has(key))continue;this.seenEvents.add(key);if(this.seenEvents.size>64)this.seenEvents.delete(Math.min(...this.seenEvents));this.onEvent(copy(event));}this.emitState();}
    finish(){if(this.result)return;this.result={resultId:this.raceId+':'+this.tickCount,raceId:this.raceId,finalTick:this.tickCount,winnerSlot:this.race.winnerSlot,finishTimes:copy(this.race.finishTimes),finalSnapshot:this.race.snapshot()};this.phase='result';this.resultSentAt=0;this.resultStartedAt=this.now();this.sendResult();this.onResult(copy(this.result));this.emitState();}
    sendResult(){this.resultSentAt=this.now();this.send('result',this.result);}
    receiveResult(message){const result=message.payload;if(!['racing','result'].includes(this.phase)||!result||result.raceId!==this.raceId||!result.resultId||!result.finalSnapshot)return;if(this.result&&this.result.resultId!==result.resultId)return;try{this.race=Engine.Race.fromSnapshot(result.finalSnapshot);}catch(_){return;}if(!this.result){this.pendingInputs.clear();this.inputBuffers={host:new Map(),guest:new Map()};this.result=copy(result);this.phase='result';this.resultStartedAt=this.now();this.onResult(copy(this.result));this.emitState();}this.send('result-ack',{resultId:result.resultId});}
    tick(dtSeconds){if(this.closed)return;const now=this.now(),rawDt=Math.max(0,Number(dtSeconds)||0),dt=Math.min(rawDt,.1);if(rawDt>.5&&['countdown','racing'].includes(this.phase))return this.abort('frame-stall');
      if(this.role==='guest'&&!this.peerId&&now>this.joinDeadline)return this.abort('join-timeout');if(this.role==='host'&&now>this.joinExpiry&&!this.race)return this.abort('room-expired');if(this.role==='guest'&&!this.peerId&&now-this.lastHelloAt>=1000){this.lastHelloAt=now;this.send('hello',{characterId:this.characterId,engineVersion:this.engineVersion,rulesVersion:this.rulesVersion});}
      if(this.peerId&&now-this.lastHeardAt>3000){if(this.phase==='result')return this.resultClose('peer-timeout');return this.abort('peer-timeout');}if(this.peerId&&now-this.lastHeardAt>(this.role==='guest'&&this.phase==='racing'?500:1500)&&this.phase!=='result')this.status('reconnecting');
      if(this.peerId&&now-this.lastHeartbeatAt>=1000){this.lastHeartbeatAt=now;this.send('heartbeat',{});} if(this.role==='guest'&&['countdown','racing'].includes(this.phase))this.flushInputs();
      if(this.role==='host'&&this.phase==='starting'&&now-this.startStartedAt>10000)return this.abort('start-timeout');if(this.role==='host'&&this.phase==='starting'&&!this.startAck&&now-this.startSentAt>=300)this.broadcastStart();
      if(this.role==='host'&&this.race&&['countdown','racing'].includes(this.phase)){this.accumulator+=dt;while(this.accumulator>=TICK){this.accumulator-=TICK;this.race.update(TICK);this.tickCount++;if(this.race.state==='racing')this.phase='racing';if(this.race.time>90)return this.abort('race-timeout');if(this.race.state==='finished'){this.finish();break;}}for(const event of this.race.events)if(!Number.isInteger(event.eventSeq)){event.eventSeq=++this.eventSeq;this.onEvent(copy(event));}if(this.race.events.length>64)this.race.events.splice(0,this.race.events.length-64);for(const slot of ['host','guest']){const queued=Array.from(this.inputBuffers[slot].values());if(queued.length&&Math.min(...queued.map(v=>v.receivedAt))<now-500)return this.abort('input-gap');}if(now-this.lastSnapshotAt>=100){this.lastSnapshotAt=now;this.send('snapshot',{tick:this.tickCount,phase:this.phase,snapshot:this.race.snapshot(),lastProcessedInputSeq:this.lastProcessedInputSeq,events:this.race.events.slice(-32)});this.emitState();}}
      if(this.result){if(this.rematchRequested&&now-this.lastRematchAt>=1000){this.lastRematchAt=now;this.send('rematch-ready',{raceId:this.raceId});}if(this.role==='host'&&!this.resultAck&&now-this.resultSentAt>=300&&now-this.resultStartedAt<10000)this.sendResult();if(this.role==='host'&&!this.resultAck&&now-this.resultStartedAt>=10000)this.resultClose('result-ack-timeout');else if(now-this.resultStartedAt>=120000)this.resultClose('result-idle');}
    }
    resultClose(reason){if(this.closed)return;this.status('result-closed',{reason});this.close();}
    abort(reason='aborted',notify=true){if(this.closed||this.phase==='aborted')return;if(this.phase==='result'){this.status('result-closed',{reason});if(notify&&this.peerId)this.send('abort',{reason});this.close();return;}this.phase='aborted';if(notify&&this.peerId)this.send('abort',{reason});this.status('aborted',{reason});this.emitState();this.close();}
    close(){if(this.closed)return;this.closed=true;if(this.unsubMessage)this.unsubMessage();if(this.unsubDisconnect)this.unsubDisconnect();if(this.transport&&this.transport.close)this.transport.close();}
  }
  return {MultiplayerSession,PROTOCOL_VERSION:VERSION};
});
