const {test}=require('node:test');
const assert=require('node:assert/strict');
const {Race,CHARACTERS,LENGTH,opponents,seeded}=require('../engine.js');
function empty(){const g=new Race('brown','gray',42);g.items=[];g.state='racing';g.think=()=>{};g.opponent.x=-2000;return g;}
function step(g,t){for(let i=0;i<Math.round(t*120);i++)g.update(1/120);}
function item(type,x,lane=1,z=0){return {id:0,type,x,lane,z,seen:new Set(),taken:false};}
test('five characters each face four unique shuffled opponents',()=>{
 assert.deepEqual(CHARACTERS.map(c=>c.name),['ぽん','うさ','むぎくん','もかちゃま','ゆずくん']);
 for(const c of CHARACTERS){const pool=opponents(c.id,seeded(77));assert.equal(pool.length,4);assert.equal(new Set(pool).size,4);assert.ok(!pool.includes(c.id));}
 assert.notDeepEqual(opponents('brown',seeded(1)),opponents('brown',seeded(2)));
});
test('countdown prevents input and movement, then starts automatically',()=>{const g=new Race('brown','gray');g.move(g.player,-1);assert.equal(g.player.lane,1);assert.equal(g.jump(g.player),false);step(g,2);assert.equal(g.player.x,0);step(g,1);assert.equal(g.state,'racing');assert.ok(g.player.x>0);});
test('lane transitions stop at three lanes and work mid-jump',()=>{const g=empty();g.move(g.player,-1);g.move(g.player,-1);assert.equal(g.player.lane,0);g.jump(g.player);g.move(g.player,1);step(g,.2);assert.ok(g.player.z>0);g.move(g.player,1);g.move(g.player,1);assert.equal(g.player.lane,2);});
test('jump lands and cannot retrigger in the air',()=>{const g=empty();assert.ok(g.jump(g.player));assert.equal(g.jump(g.player),false);step(g,.5);assert.ok(g.player.z>48);step(g,.5);assert.equal(g.player.z,0);assert.ok(g.jump(g.player));});
test('acorn collects once, boosts temporarily, then returns to base speed',()=>{const g=empty();g.items=[item('acorn',100)];step(g,1);assert.equal(g.player.acorns,1);assert.equal(g.player.collected,1);assert.ok(g.player.speed>400);step(g,4);assert.equal(g.player.boost,0);assert.ok(Math.abs(g.player.speed-300)<1);});
test('rock drops at most three acorns, cancels boost, and respects immunity',()=>{const g=empty();g.player.acorns=5;g.player.boost=2;g.items=[item('rock',90)];step(g,.4);assert.equal(g.player.acorns,2);assert.equal(g.player.boost,0);assert.ok(g.player.slow>0);assert.equal(g.player.hits,1);g.hit(g.player);assert.equal(g.player.hits,1);step(g,2);assert.ok(g.player.speed>270);});
test('empty inventory never goes negative',()=>{const g=empty();g.hit(g.player);assert.equal(g.player.acorns,0);assert.ok(g.player.slow>0);});
test('jump clears rock; adjacent lane avoids rock',()=>{let g=empty();g.items=[item('rock',155)];g.jump(g.player);step(g,1);assert.equal(g.player.hits,0);g=empty();g.items=[item('rock',250,0)];step(g,1);assert.equal(g.player.hits,0);});
test('ramp launches automatically and clears the next rock',()=>{const g=empty();g.items=[item('ramp',100),item('rock',305)];step(g,1.5);assert.equal(g.player.jumps,1);assert.equal(g.player.hits,0);assert.ok(g.events.some(e=>e.type==='ramp'));});
test('a boosted car is relaunched by the next ramp before it lands',()=>{const g=empty();g.player.speed=430;g.player.boost=99;g.items=[item('ramp',100),item('rock',305),item('ramp',520),item('rock',725)];step(g,2);assert.equal(g.player.jumps,2);assert.equal(g.player.hits,0);assert.equal(g.events.filter(e=>e.type==='ramp').length,2);});
test('ramp acorn follows the flight arc and is collected after a clean jump',()=>{const g=empty();const reward={...item('acorn',270),z:170,rampBonus:true};g.items=[item('ramp',100),item('rock',305),reward];step(g,1.3);assert.equal(reward.taken,true);assert.equal(g.player.collected,1);assert.equal(g.player.hits,0);});
test('car contact penalizes both; separate lanes do not',()=>{const g=empty();g.opponent.x=0;g.opponent.y=g.opponent.lane=1;g.player.acorns=2;g.opponent.acorns=3;step(g,.1);assert.equal(g.player.hits,1);assert.equal(g.opponent.hits,1);assert.equal(g.player.acorns,0);const h=empty();h.opponent.x=0;step(h,.1);assert.equal(h.player.hits,0);});
test('car collision drops acorns, bounces all lane centers, and locks steering briefly',()=>{for(const lane of [0,1,2]){const g=new Race('brown','brown',51+lane,0,{mode:'multiplayer'});g.items=[];g.state='racing';g.player.x=g.opponent.x=0;g.player.y=g.player.lane=lane;g.opponent.y=g.opponent.lane=lane;g.player.acorns=g.opponent.acorns=4;g.update(1/120);const expected=lane===0?[0,1]:lane===1?[0,2]:[1,2];assert.deepEqual([g.player.lane,g.opponent.lane].sort(),expected);assert.equal(g.player.acorns,1);assert.equal(g.opponent.acorns,1);assert.equal(g.player.knockback,.35);assert.equal(g.player.jumps,0);assert.ok(g.player.vz>=260);const laneBefore=g.player.lane;g.move(g.player,laneBefore>0?-1:1);assert.equal(g.player.lane,laneBefore);const hits=g.player.hits;g.update(1/120);assert.equal(g.player.hits,hits);step(g,.4);g.move(g.player,laneBefore>0?-1:1);assert.notEqual(g.player.lane,laneBefore);}});
test('rock slow remains long while collision slow is short',()=>{const g=empty();g.player.acorns=3;g.hit(g.player);assert.equal(g.player.slow,1.45);const h=empty();h.player.x=h.opponent.x=0;h.opponent.y=h.opponent.lane=h.player.lane;h.collide(h.player,h.opponent);assert.equal(h.player.slow,.45);});
test('shared acorn belongs to first arriving car',()=>{const g=empty();g.opponent.x=70;g.opponent.lane=g.opponent.y=1;g.player.x=0;g.items=[item('acorn',110)];step(g,.15);/* Wider pickup reaches this acorn before the existing first-frame car ram; ownership remains gray even though that ram spends it. */assert.equal(g.opponent.collected,1);assert.equal(g.player.collected,0);});
test('collectibles forgive a late lane entry but keep full lanes and old obstacle reach strict',()=>{for(const slot of ['player','opponent']){const g=new Race('brown','gray',17,0,{mode:'multiplayer'});g.items=[];g.state='racing';const r=g[slot];r.x=150;r.lane=1;r.y=.4;g.items=[item('acorn',100,1)];g.update(1/120);assert.equal(r.acorns,1);}const outside=empty();outside.player.x=176;outside.items=[item('acorn',100,1)];outside.update(1/120);assert.equal(outside.player.acorns,0);const adjacent=empty();adjacent.player.x=150;adjacent.player.y=adjacent.player.lane=0;adjacent.items=[item('gold',100,1)];adjacent.update(1/120);assert.equal(adjacent.player.gold,0);const rock=empty();rock.player.x=0;rock.player.lane=1;rock.player.y=.4;rock.items=[item('rock',40,1)];rock.update(1/120);assert.equal(rock.player.hits,0);});
test('collectible height misses can retry while overlapping',()=>{const g=empty();g.player.x=10;g.player.z=200;const acorn=item('acorn',50,1);g.items=[acorn];g.update(1/120);assert.equal(acorn.taken,false);assert.equal(acorn.seen.size,0);g.player.z=0;g.update(1/120);assert.equal(acorn.taken,true);assert.equal(g.player.acorns,1);});
test('pause freezes simulation state',()=>{const g=empty();g.state='paused';step(g,5);assert.equal(g.time,0);assert.equal(g.player.x,0);});
test('finish crossing order determines winner on same update',()=>{const g=empty();g.player.x=LENGTH-1;g.opponent.x=LENGTH-2;g.update(1/120);assert.equal(g.winner,'brown');assert.equal(g.state,'finished');const x=g.player.x;step(g,3);assert.equal(g.player.x,x);});
test('opponent can win',()=>{const g=empty();g.opponent.x=LENGTH-1;g.update(1/120);assert.equal(g.winner,'gray');});
test('full stage finishes for every character and round',()=>{for(const c of CHARACTERS)for(let round=0;round<4;round++){const rival=opponents(c.id,seeded(1))[round];const g=new Race(c.id,rival,200+round,round);step(g,65);assert.equal(g.state,'finished');assert.ok(g.time>20&&g.time<60);for(const type of ['ramp','rock','acorn'])assert.ok(g.items.some(i=>i.type===type));}});
test('difficulty increases by round and gold appears only from round two',()=>{const {DIFFICULTY}=require('../engine.js');for(let i=0;i<4;i++){const g=new Race('brown','gray',31,i);assert.equal(g.items.filter(it=>it.type==='gold').length,[0,2,3,4][i]);if(i)for(const key of ['speed','dodge','food'])assert.ok(DIFFICULTY[i][key]>DIFFICULTY[i-1][key]);}assert.equal(DIFFICULTY[3].speed,300);assert.ok(DIFFICULTY[3].dodge<1);});
test('gold replaces normal boost, does not stack, expires, and contact cancels it',()=>{const g=empty();g.player.boost=2;g.collect(g.player,item('gold',0));assert.equal(g.player.boost,0);assert.equal(g.player.gold,1.5);g.collect(g.player,item('acorn',0));assert.equal(g.player.boost,0);step(g,1);assert.ok(g.player.speed>590&&g.player.speed<=600);step(g,1.5);assert.equal(g.player.gold,0);assert.ok(g.player.speed<301);g.collect(g.player,item('gold',0));g.hit(g.player);assert.equal(g.player.gold,0);});
test('help belongs to trailing car on either side; leader cannot collect it',()=>{for(const trailing of ['player','opponent']){const g=empty();g.player.x=1000;g.opponent.x=1000;g[trailing].x=300;g.help(.01);const h=g.items.find(it=>it.type==='help');assert.equal(h.owner,g[trailing].id);const leader=g[trailing=== 'player'?'opponent':'player'];g.collect(leader,h);assert.equal(h.taken,false);g.collect(g[trailing],h);assert.equal(h.taken,true);assert.equal(g[trailing].acorns,1);assert.equal(g[trailing].boost,2.8);}});
test('help requires gap, respects cooldown, expires, avoids rocks and stays before finish',()=>{const g=empty();g.opponent.x=599;g.help(.1);assert.ok(!g.items.length);g.opponent.x=700;g.items=[item('rock',240,1)];g.help(.1);let h=g.items.find(it=>it.type==='help');assert.notEqual(h.lane,1);g.collect(g.player,h);g.help(5);assert.equal(g.items.filter(it=>it.type==='help').length,0);g.help(1);h=g.items.find(it=>it.type==='help');assert.ok(h);g.time=h.expires;g.help(0);assert.ok(!g.items.some(it=>it.type==='help'));g.helpCooldown=0;g.player.x=LENGTH-300;g.opponent.x=LENGTH+500;g.help(1);assert.ok(!g.items.some(it=>it.type==='help'));});
test('leader passes through trailing-only help without taking it',()=>{const g=empty();g.opponent.x=0;g.player.x=-700;g.opponent.y=g.opponent.lane=1;g.helpCooldown=6;const h={...item('help',50),owner:g.player.id,spawned:0,expires:4};g.items=[h];step(g,.3);assert.equal(h.taken,false);assert.equal(g.opponent.acorns,0);});
test('every second large-gap help is golden per trailing multiplayer slot and survives snapshots',()=>{const g=new Race('brown','brown',66,0,{mode:'multiplayer'});g.items=[];g.state='racing';g.player.x=0;g.opponent.x=1100;g.help(.01);let h=g.items[0];assert.equal(h.golden,false);g.collect(g.opponent,h);assert.equal(h.taken,false);g.collect(g.player,h);assert.equal(h.taken,true);g.helpCooldown=0;g.items=[];g.help(.01);h=g.items[0];assert.equal(h.golden,true);g.collect(g.player,h);assert.equal(g.player.gold,1.5);assert.ok(g.events.some(e=>e.type==='gold'&&e.slot==='host'));g.helpCooldown=0;g.items=[];g.player.x=1100;g.opponent.x=0;g.help(.01);assert.equal(g.items[0].golden,false);g.helpCooldown=0;g.items=[];g.help(.01);assert.equal(g.items[0].golden,true);const restored=Race.fromSnapshot(g.snapshot());assert.deepEqual(restored.helpCounters,g.helpCounters);assert.equal(restored.items[0].golden,true);const near=new Race('brown','gray',1,0,{mode:'multiplayer'});near.items=[];near.state='racing';near.opponent.x=999;near.help(.1);assert.equal(near.items.length,1);assert.equal(near.items[0].golden,false);});
