// Run real UI handlers in a tiny DOM harness to verify tournament state separately
// from browser screenshots and physical touch acceptance.
const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..');
async function app(portrait=false){
 const elements=new Map(),canvasLines=[],canvasText=[],context2d=new Proxy({createLinearGradient:()=>({addColorStop(){}}),lineTo(...v){canvasLines.push(v)},fillText(v){canvasText.push(v)}},{get:(t,k)=>t[k]||(()=>{})});
 function el(){return {hidden:false,textContent:'',style:{},dataset:{},children:[],listeners:{},attrs:{},classList:{add(){},remove(){},toggle(){}},append(...v){this.children.push(...v)},replaceChildren(...v){this.children=v},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.listeners[k]=f},getContext(){return context2d},focus(){},setPointerCapture(){}};}
 const document={hidden:false,body:el(),getElementById(id){if(!elements.has(id))elements.set(id,el());return elements.get(id)},createElement:el,querySelectorAll(){return elements.get('characters').children},addEventListener(){}};
 class Image{set src(v){this.onload();}}
 const sandbox={document,console,Image,performance:{now:()=>0},requestAnimationFrame(){},addEventListener(){},matchMedia:()=>({matches:portrait,addEventListener(){}}),Math:Object.create(Math)};
 sandbox.Math.random=require('../engine.js').seeded(81);sandbox.window=sandbox;
 const c=vm.createContext(sandbox);for(const f of ['engine.js','assets/bounds.js','game.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),c);
 await new Promise(setImmediate);return {run:s=>vm.runInContext(s,c),elements,canvasLines,canvasText,snapshot:()=>c.raceSnapshot()};
}
test('all five cards load and selection changes the player flag in real time',async()=>{const a=await app();const cards=a.elements.get('characters').children;assert.equal(cards.length,5);const before=a.canvasLines.length;cards[2].listeners.click();assert.equal(a.snapshot().selected,'mugi');assert.ok(a.canvasLines.length>before);a.elements.get('start').listeners.click();assert.equal(a.snapshot().player.id,'mugi');assert.ok(!a.snapshot().order.includes('mugi'));});
test('first race guide pauses once, gold guide appears before its course, and help reopens it',async()=>{const a=await app();a.run('startTournament()');assert.equal(a.elements.get('guide').hidden,false);assert.equal(a.elements.get('guide-title').textContent,'どんぐりで加速');assert.equal(a.snapshot().state,'paused');a.elements.get('guide-close').onclick();assert.equal(a.elements.get('guide').hidden,true);assert.equal(a.snapshot().state,'countdown');a.run("race.state='racing';race.items=[{type:'gold',x:500,lane:1,z:0,seen:new Set(),taken:false}];frame(100);frame(150)");assert.equal(a.elements.get('guide').hidden,true);a.run('round=1;startRace()');assert.equal(a.elements.get('guide-title').textContent,'金色どんぐり');assert.equal(a.snapshot().state,'paused');a.elements.get('guide-close').onclick();a.elements.get('help').onclick();assert.equal(a.elements.get('guide-title').textContent,'どんぐり');assert.match(a.elements.get('guide-detail').textContent,/金色：2倍速/);});
test('four wins advance through distinct rivals to championship and restart',async()=>{const a=await app();a.run('startTournament()');const pool=a.snapshot().order;for(let i=0;i<4;i++){
 assert.equal(a.snapshot().round,i);assert.equal(a.snapshot().opponent.id,pool[i]);
 a.run("race.winner=selected;race.state='finished';finish()");
 assert.equal(a.elements.get('dialog').hidden,false);
 if(i<3){assert.match(a.elements.get('result-detail').textContent,/次の相手/);a.elements.get('continue').onclick();}
 }
 assert.equal(a.elements.get('dialog-title').textContent,'優勝！');assert.equal(a.elements.get('wins').children.filter(s=>s.className==='won').length,4);
 a.elements.get('continue').onclick();assert.equal(a.snapshot().round,0);assert.equal(a.snapshot().state,'countdown');
});
test('losing retry preserves opponent, order, and prior wins; choose again resets UI',async()=>{const a=await app();a.run('startTournament();round=2;startRace()');const before=a.snapshot();a.run("race.winner=race.opponent.id;race.state='finished';finish()");assert.equal(a.elements.get('continue').textContent,'同じ相手に再挑戦');a.elements.get('continue').onclick();assert.equal(a.snapshot().round,2);assert.deepEqual(a.snapshot().order,before.order);assert.equal(a.snapshot().opponent.id,before.opponent.id);a.elements.get('back').onclick();assert.equal(a.snapshot().view,'selection');assert.equal(a.snapshot().player,null);});
test('pause/resume restores countdown or racing, and control handlers affect the car',async()=>{const a=await app();a.run('startTournament()');a.elements.get('guide-close').onclick();a.run('pause()');assert.equal(a.snapshot().state,'paused');a.run('resume()');assert.equal(a.snapshot().state,'countdown');a.run("race.state='racing'");const e={preventDefault(){},pointerId:1};a.elements.get('up').listeners.pointerdown(e);assert.equal(a.snapshot().player.lane,0);a.elements.get('down').listeners.pointerdown(e);assert.equal(a.snapshot().player.lane,1);a.elements.get('jump').listeners.pointerdown(e);assert.ok(a.snapshot().player.vz>0);a.run('pause();resume()');assert.equal(a.snapshot().state,'racing');});
test('only the selected racer gets a flag and racer labels are not drawn',async()=>{const a=await app();a.canvasLines.length=0;a.canvasText.length=0;a.run("startTournament();race.state='racing';car(race.player,0)");assert.equal(a.canvasLines.length,3);assert.deepEqual(a.canvasText,[]);a.canvasLines.length=0;a.run('car(race.opponent,0)');assert.equal(a.canvasLines.length,0);assert.deepEqual(a.canvasText,[]);});

test('portrait fallback unblocks the race and pause/resume without OS rotation',async()=>{const a=await app(true);assert.equal(a.run('orientationBlocked()'),true);a.elements.get('play-rotated').onclick();assert.equal(a.run('orientationBlocked()'),false);a.run('startTournament()');a.elements.get('guide-close').onclick();a.run('frame(100);frame(150)');assert.ok(a.run('race.countdown')<2.6);a.run('pause();resume()');assert.equal(a.snapshot().state,'countdown');a.run("race.state='racing'");a.elements.get('down').listeners.pointerdown({preventDefault(){},pointerId:1});assert.equal(a.snapshot().player.lane,2);});
test('nearby-play lobby keeps the existing character cards usable before a connection is ready',async()=>{const a=await app();a.elements.get('multiplayer-start').onclick();assert.equal(a.run('view'),'lobby');assert.equal(a.elements.get('selection').hidden,false);assert.equal(a.elements.get('select-bottom').hidden,true);assert.equal(a.elements.get('multiplayer').hidden,false);assert.equal(a.elements.get('multiplayer-ready').disabled,true);a.elements.get('characters').children[3].listeners.click();assert.equal(a.snapshot().selected,'mocha');assert.equal(a.elements.get('multiplayer-ready').textContent,'もかちゃまで準備できた');});
test('multiplayer controller ticks lobby and result phases and survives a synchronous abort',async()=>{const a=await app();a.run("var multiplayerSteps=0;multiplayer={race:null,localSlot:'host',tick(){multiplayerSteps++;}};view='lobby';frame(10);frame(610);view='result';frame(710)");assert.equal(a.run('multiplayerSteps'),3);assert.doesNotThrow(()=>a.run("multiplayer={race:null,localSlot:'host',tick(){multiplayer=null;}};view='lobby';frame(810)"));});
test('multiplayer HUD replaces the tournament stage and help stays nonblocking',async()=>{const a=await app();a.run("multiplayer={localSlot:'host',race:new Race('brown','gray')};race=multiplayer.race;view='lobby';enterMultiplayerRace()");assert.equal(a.elements.get('stage-label').textContent,'近くの人と対戦');assert.equal(a.elements.get('stage-name').textContent,'1回勝負');a.elements.get('help').onclick();assert.equal(a.elements.get('guide').hidden,true);assert.equal(a.elements.get('status-text').textContent,'対戦中は止めずに走ろう。');});
test('guest lane display keeps unacknowledged moves and eases without snapping backward',async()=>{const a=await app();const trace=JSON.parse(a.run("multiplayer={localSlot:'guest',phase:'racing',pendingInputs:new Map()};multiplayerTargets={host:{id:'brown',lane:0,y:0,x:0,z:0,vz:0,speed:300},guest:{id:'gray',lane:1,y:1,x:0,z:0,vz:0,speed:300}};multiplayerDisplay={host:{...multiplayerTargets.host},guest:{...multiplayerTargets.guest}};multiplayer.pendingInputs.set(7,{action:'down'});predictMultiplayerInput('down');const yAfterPredict=multiplayerDisplay.guest.y;multiplayer.pendingInputs.set(8,{action:'down'});predictMultiplayerInput('down');const targetBeforeAck=multiplayerDisplay.guest.targetLane;const values=[];for(let i=0;i<6;i++){stepMultiplayerDisplay(1/60);values.push(multiplayerDisplay.guest.y);}multiplayer.pendingInputs.clear();multiplayerTargets.guest.lane=2;multiplayerTargets.guest.y=1;refreshGuestDisplayLane();const beforeAckStep=multiplayerDisplay.guest.y;stepMultiplayerDisplay(1/60);const ackTarget=multiplayerDisplay.guest.targetLane;multiplayerTargets.guest.lane=1;multiplayer.pendingInputs=new Map([[10,{action:'down'}],[11,{action:'down'}],[12,{action:'up'}]]);refreshGuestDisplayLane();JSON.stringify({yAfterPredict,values,targetBeforeAck,ackTarget,beforeAckStep,afterAckStep:multiplayerDisplay.guest.y,opposingTarget:multiplayerDisplay.guest.targetLane})"));assert.equal(trace.yAfterPredict,1,'input only changes the display target, never teleports y');assert.equal(trace.targetBeforeAck,2);assert.equal(trace.ackTarget,2);assert.equal(trace.opposingTarget,1,'repeated down/down/up inputs clamp from lane 1 back to lane 1');assert.ok(trace.values[0]>1&&trace.values[0]<2,'lane movement is eased after input');for(let i=1;i<trace.values.length;i++)assert.ok(trace.values[i]>trace.values[i-1],'stale snapshots must not pull the lane backward');assert.ok(trace.afterAckStep>trace.beforeAckStep,'ACK handoff keeps moving toward the same lane');});
test('guest knockback follows the forced lane without replaying pre-hit display inputs',async()=>{const a=await app();const trace=JSON.parse(a.run("multiplayer={localSlot:'guest',phase:'racing',pendingInputs:new Map([[7,{action:'down'}]])};multiplayerTargets={host:{id:'brown',lane:1,y:1,x:0,z:0,vz:0,speed:300},guest:{id:'gray',lane:0,y:0,x:0,z:0,vz:0,speed:300,knockback:.35}};multiplayerDisplay={host:{...multiplayerTargets.host},guest:{...multiplayerTargets.guest,y:1}};refreshGuestDisplayLane();const targetDuringHit=multiplayerDisplay.guest.targetLane;predictMultiplayerInput('down');const yAfterInput=multiplayerDisplay.guest.y;stepMultiplayerDisplay(1/60);const yDuringHit=multiplayerDisplay.guest.y;multiplayerTargets.guest.knockback=0;refreshGuestDisplayLane();const targetWithPreHitPending=multiplayerDisplay.guest.targetLane;multiplayer.pendingInputs.clear();multiplayer.pendingInputs.set(8,{action:'down'});refreshGuestDisplayLane();JSON.stringify({targetDuringHit,yAfterInput,yDuringHit,targetWithPreHitPending,targetAfterNewInput:multiplayerDisplay.guest.targetLane})"));assert.equal(trace.targetDuringHit,0);assert.equal(trace.yAfterInput,1,'a locked lane does not teleport after input');assert.ok(trace.yDuringHit<1&&trace.yDuringHit>0,'the displayed lane eases toward the forced target');assert.equal(trace.targetWithPreHitPending,0,'pre-hit pending input is not replayed after the lock');assert.equal(trace.targetAfterNewInput,1,'new input after the lock can move from the forced lane');});
test('a rematch race ID resets guest display from the new start instead of easing back from the goal',async()=>{const a=await app();const state=JSON.parse(a.run("const first=new Race('brown','gray');first.player.x=12000;first.opponent.x=11900;multiplayer={localSlot:'guest',phase:'result',race:first,pendingInputs:new Map()};multiplayerState({raceId:'round-one',phase:'result'});multiplayerDisplay.guest.x=11800;const next=new Race('brown','gray');multiplayer.race=next;multiplayer.phase='countdown';multiplayerState({raceId:'round-two',phase:'countdown'});JSON.stringify({raceId:multiplayerDisplayRaceId,x:multiplayerDisplay.guest.x,y:multiplayerDisplay.guest.y})"));assert.equal(state.raceId,'round-two');assert.equal(state.x,0);assert.equal(state.y,0);});
test('multiplayer result requests a same-room rematch and preserves the result when it closes',async()=>{const a=await app();a.run("var rematchCalls=0;multiplayer={localSlot:'host',phase:'result',race:new Race('brown','gray'),requestRematch(){rematchCalls++;return true;}};race=multiplayer.race;multiplayerResult({winnerSlot:'host'})");assert.equal(a.elements.get('continue').textContent,'もう一度あそぶ');assert.equal(a.elements.get('wins').hidden,true);a.elements.get('continue').onclick();assert.equal(a.run('rematchCalls'),1);assert.equal(a.elements.get('continue').disabled,true);assert.equal(a.elements.get('result-detail').textContent,'相手の準備を待っています。');a.run("multiplayerStatus({status:'rematch-offered'})");assert.equal(a.elements.get('continue').disabled,false);assert.equal(a.elements.get('result-detail').textContent,'相手がもう一度あそぶのを待っています。');a.run("multiplayerStatus({status:'result-closed',reason:'result-idle'})");assert.equal(a.elements.get('continue').disabled,true);assert.match(a.elements.get('result-detail').textContent,/新しい部屋/);});
